"""empty message

Revision ID: c4e1fff66cb9
Revises: cc656ce5f8e9
Create Date: 2022-01-23 17:31:29.436355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e1fff66cb9'
down_revision = 'cc656ce5f8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('questionId', sa.Integer(), nullable=True),
    sa.Column('answerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answerId'], ['answer.id'], name=op.f('fk_comment_answerId_answer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questionId'], ['question.id'], name=op.f('fk_comment_questionId_question'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('fk_comment_userId_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
