"""empty message

Revision ID: cc656ce5f8e9
Revises: b86fe271587e
Create Date: 2022-01-23 15:13:47.127842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc656ce5f8e9'
down_revision = 'b86fe271587e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updatedAt', sa.DateTime(), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updatedAt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('updatedAt')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('updatedAt')

    # ### end Alembic commands ###
